/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DineroFaucet, DineroFaucetInterface } from "../DineroFaucet";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract Dinero",
        name: "_dinero",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "DINERO",
    outputs: [
      {
        internalType: "contract Dinero",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161024a38038061024a83398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b6080516101b9610091600039600081816040015261010301526101b96000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80637790df391461003b578063a0712d681461007e575b600080fd5b6100627f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200160405180910390f35b61009161008c36600461016a565b610093565b005b806934f086f3b33b6840000010156100e75760405162461bcd60e51b815260206004820152601360248201527208c867440c2dadeeadce840e8dede40d0d2ced606b1b604482015260640160405180910390fd5b6040516340c10f1960e01b8152336004820152602481018290527f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316906340c10f1990604401600060405180830381600087803b15801561014f57600080fd5b505af1158015610163573d6000803e3d6000fd5b5050505050565b60006020828403121561017c57600080fd5b503591905056fea26469706673582212203bf6178e118959c9558d6e395007f04fb5892a2a327f1b9ba0eafad70b96f72464736f6c634300080a0033";

export class DineroFaucet__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _dinero: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DineroFaucet> {
    return super.deploy(_dinero, overrides || {}) as Promise<DineroFaucet>;
  }
  getDeployTransaction(
    _dinero: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_dinero, overrides || {});
  }
  attach(address: string): DineroFaucet {
    return super.attach(address) as DineroFaucet;
  }
  connect(signer: Signer): DineroFaucet__factory {
    return super.connect(signer) as DineroFaucet__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DineroFaucetInterface {
    return new utils.Interface(_abi) as DineroFaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DineroFaucet {
    return new Contract(address, _abi, signerOrProvider) as DineroFaucet;
  }
}
